const ROOT_URL = process.env.REACT_APP_ROOT_URL,
  allPatientsUrl = `${ROOT_URL}/doctor/all/patients`,
  userAuthUrl = `${ROOT_URL}/login`,
  patientRegisterUrl = `${ROOT_URL}/signup`,
  logoutUserUrl = `${ROOT_URL}/signOut`,
  getMaxScoreUrl = `${ROOT_URL}/doctor/patient/maxscore`,
  singlePatientUrl = patientID => `${ROOT_URL}/doctor/${patientID}`,
  postNotificationUrl = `${ROOT_URL}/doctor/sendmail`,
  getNotificationsUrl = patientID => `${ROOT_URL}/doctor/getmail/${patientID}`,
  deletePatientUrl = patientID => `${ROOT_URL}/doctor/delete/${patientID}`,
  editPatientUrl = patientID => `${ROOT_URL}/doctor/update/${patientID}`,
  getMinMaxRomUrl = patientID => `${ROOT_URL}/doctor/patient/rom/${patientID}`,
  feedbackUrl = `https://goo.gl/forms/3r1X41CBf2I7wrpv1`;

export {
  allPatientsUrl,
  userAuthUrl,
  patientRegisterUrl,
  logoutUserUrl,
  getMaxScoreUrl,
  singlePatientUrl,
  postNotificationUrl,
  getNotificationsUrl,
  deletePatientUrl,
  editPatientUrl,
  getMinMaxRomUrl,
  feedbackUrl,
};
